[package]
name = "spongify"
version = "0.1.0"
authors = ["Travis Gockel <travis@gockelhut.com>"]
edition = "2021"

[dependencies]
clap = { version = "^4.4.7", features = ["derive"] }
copypasta-ext = "^0.4.4"
rand = "^0.8.5"
